<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-08T18:13:06 GMT-06:00" name="Surefire suite" finished-at="2023-08-08T18:14:05 GMT-06:00" duration-ms="58912">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.LoginErrorValidation()[pri:0, instance:automationprojects.tests.ErrorValidationsTest@31d7b7bf]" name="LoginErrorValidation" class="automationprojects.tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.SubmitOrder(java.util.HashMap)[pri:0, instance:automationprojects.tests.SubmitOrderTest@1139b2f3]" name="SubmitOrder" class="automationprojects.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-08-08T18:13:06 GMT-06:00" name="Surefire test" finished-at="2023-08-08T18:14:05 GMT-06:00" duration-ms="58912">
      <class name="automationprojects.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationprojects.tests.SubmitOrderTest@1139b2f3]" started-at="2023-08-08T18:13:37 GMT-06:00" name="launchApplication" finished-at="2023-08-08T18:13:44 GMT-06:00" duration-ms="7924" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:automationprojects.tests.SubmitOrderTest@1139b2f3]" started-at="2023-08-08T18:13:44 GMT-06:00" name="SubmitOrder" data-provider="getData" finished-at="2023-08-08T18:13:49 GMT-06:00" duration-ms="4092" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Bhuvana12, product=ZARA COAT 3, email=balasingamji@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationprojects.tests.SubmitOrderTest@1139b2f3]" started-at="2023-08-08T18:13:49 GMT-06:00" name="tearDown" finished-at="2023-08-08T18:13:49 GMT-06:00" duration-ms="91" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationprojects.tests.SubmitOrderTest@1139b2f3]" started-at="2023-08-08T18:13:49 GMT-06:00" name="launchApplication" finished-at="2023-08-08T18:13:55 GMT-06:00" duration-ms="6141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:automationprojects.tests.SubmitOrderTest@1139b2f3]" started-at="2023-08-08T18:13:55 GMT-06:00" name="SubmitOrder" data-provider="getData" finished-at="2023-08-08T18:13:59 GMT-06:00" duration-ms="3939" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sunmoon12, product=ADIDAS ORIGINAL, email=sunmoon1992@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationprojects.tests.SubmitOrderTest@1139b2f3]" started-at="2023-08-08T18:13:59 GMT-06:00" name="tearDown" finished-at="2023-08-08T18:13:59 GMT-06:00" duration-ms="89" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationprojects.tests.SubmitOrderTest@1139b2f3]" started-at="2023-08-08T18:13:59 GMT-06:00" name="launchApplication" finished-at="2023-08-08T18:14:04 GMT-06:00" duration-ms="5402" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:automationprojects.tests.SubmitOrderTest@1139b2f3]" started-at="2023-08-08T18:14:04 GMT-06:00" name="OrderHistoryTest" finished-at="2023-08-08T18:14:05 GMT-06:00" depends-on-methods="automationprojects.tests.SubmitOrderTest.SubmitOrder" duration-ms="954" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationprojects.tests.SubmitOrderTest@1139b2f3]" started-at="2023-08-08T18:14:05 GMT-06:00" name="tearDown" finished-at="2023-08-08T18:14:05 GMT-06:00" duration-ms="101" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- automationprojects.tests.SubmitOrderTest -->
      <class name="automationprojects.tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationprojects.tests.ErrorValidationsTest@31d7b7bf]" started-at="2023-08-08T18:13:06 GMT-06:00" name="launchApplication" finished-at="2023-08-08T18:13:14 GMT-06:00" duration-ms="7186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:automationprojects.tests.ErrorValidationsTest@31d7b7bf]" started-at="2023-08-08T18:13:14 GMT-06:00" name="LoginErrorValidation" finished-at="2023-08-08T18:13:15 GMT-06:00" duration-ms="1164" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at automationprojects.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:169)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:88)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationprojects.tests.ErrorValidationsTest@31d7b7bf]" started-at="2023-08-08T18:13:15 GMT-06:00" name="tearDown" finished-at="2023-08-08T18:13:15 GMT-06:00" duration-ms="117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationprojects.tests.ErrorValidationsTest@31d7b7bf]" started-at="2023-08-08T18:13:15 GMT-06:00" name="launchApplication" finished-at="2023-08-08T18:13:20 GMT-06:00" duration-ms="5568" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:automationprojects.tests.ErrorValidationsTest@31d7b7bf]" started-at="2023-08-08T18:13:20 GMT-06:00" name="LoginErrorValidation" finished-at="2023-08-08T18:13:22 GMT-06:00" duration-ms="1094" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at automationprojects.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:169)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:88)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationprojects.tests.ErrorValidationsTest@31d7b7bf]" started-at="2023-08-08T18:13:22 GMT-06:00" name="tearDown" finished-at="2023-08-08T18:13:22 GMT-06:00" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationprojects.tests.ErrorValidationsTest@31d7b7bf]" started-at="2023-08-08T18:13:22 GMT-06:00" name="launchApplication" finished-at="2023-08-08T18:13:28 GMT-06:00" duration-ms="6032" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:automationprojects.tests.ErrorValidationsTest@31d7b7bf]" started-at="2023-08-08T18:13:28 GMT-06:00" name="ProductErrorValidation" finished-at="2023-08-08T18:13:36 GMT-06:00" duration-ms="8641" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationprojects.tests.ErrorValidationsTest@31d7b7bf]" started-at="2023-08-08T18:13:36 GMT-06:00" name="tearDown" finished-at="2023-08-08T18:13:36 GMT-06:00" duration-ms="90" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- automationprojects.tests.ErrorValidationsTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
